on:
  push
jobs:
  snykjob:
    name: snyk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Snyk
      uses: snyk/actions@0.3.0
      with:
        command: test
        json: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
