name: NodeJS CI
on:
        push:
                branches: [ master ]
jobs:
        build:
                runs-on: ubuntu-latest
                strategy:
                        matrix:
                                versions: [10.x, 12.x, 14.x]
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: Setup Node
                          uses: actions/setup-node@v1
                          with:
                                  node-version: ${{ matrix.versions }}
                        - run: npm install --package-lock-only
                        - run: npm audit || echo done
