name: nodejs CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        node: [10.x, 12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm install
          npm audit --json > audit-report.json || echo Problems Found
          npm install -g retire
          retire --path `pwd` --outputformat json --exitwith 0 --outputpath `pwd`/retire-report.json
      - name: Generate Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Audit & Retire report
          path: |
            ./audit-report.json
            ./retire-report.json
