name: NodeJS CI with Nodejsscan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          npm install
          npm audit --json > audit-report.json || echo Problems Found
          npm install -g retire
          retire --path `pwd` --outputformat json --exitwith 0 --outputpath `pwd`/retire-report.json
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: [ 3.x ]
          architecture: x64
      - run: |
          pip3 install nodejsscan
          nodejsscan --directory `pwd` --output nodejsscan-report.json
      - name: Generate Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: |
            ./audit-report.json
            ./retire-report.json
            ./nodejsscan-report.json
