name: Nodejs Action (two.yml)

on:
        pull_request:
                branches: [ master ]
        push:
                branches: [ master ]

jobs:
  test:
    name: Nodejs Audit
    runs-on: ubuntu-latest
    steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                      node-version: 12.x
            - run: ls
            - run: |
                    npm --version
                    node --version
            - run: |
                    npm install
                    npm audit --json > audit-report.json || echo done
            - run: |
                    npm install -g retire
                    retire --path . --outputformat json --outputpath ./retire-report.json --exitwith 0
            - name: Generate Artifacts
              uses: actions/upload-artifact@v2
              with:
                      name: reports
                      path: |
                              ./audit-report.json
                              ./retire-report.json
