name: nodejs CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          npm install
          npm audit --json > audit_report.json || echo Problems Found
          npm install -g retire
          retire --path `pwd` --outputformat json --exitwith 0 --outputpath `pwd`/retire-report.json
      - name: Generate Artifacts
        uses: actions/upload-artifact@v2
        with:
          - name: Audit report
            path: ./audit-report.json
          - name: Retire report
            path: ./retire-report.json
